# Generated by Django 5.0.7 on 2024-07-10 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_NAME', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Phone', models.BigIntegerField()),
                ('Message', models.TextField()),
                ('Created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_NAME', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PASSWORD', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=25)),
                ('DESCRIPTION', models.TextField()),
                ('VENUE_NAME', models.CharField(max_length=25)),
                ('ADDRESS', models.TextField()),
                ('DATE', models.DateField()),
                ('Booking_from', models.DateField()),
                ('Booking_To', models.DateField()),
                ('CREATED_AT', models.DateField(default=django.utils.timezone.now)),
                ('CITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.city')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.country')),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.eventcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_date', models.DateField()),
                ('Status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Credit card', 'Credit card'), ('Debit card', 'Debit card'), ('Digital wallet', 'Digital wallet')], max_length=25)),
                ('Payment_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=25)),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.booking')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.event')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_NAME', models.CharField(max_length=25)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.country')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='State_NAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.state'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Comment', models.TextField()),
                ('Review_date', models.DateField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscoverLocal.user')),
            ],
        ),
    ]
