# Generated by Django 5.0.7 on 2024-07-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscoverLocal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='DATE',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.IntegerField(),
        ),
    ]
